### ISSUE TITLE
Cod scris aiurea

### ISSUE THREAD

**Issue by davidutzus** [2Parale/2PCMS#5]
am instalat 2pcms pe local folosind WAMP, dupa ce am reusit instalarea foarte simpla de altfel am observat ca toata pagina era plina de coduri care nu erau procesate corect m-am uitat putin prin sursa is am observat ca peste tot este folosit <? cod ?>  in loc de <?php cod ?> plus cereri de forma <?=$_CONFIG["urlpath"]?> in loc de <?php $_CONFIG["urlpath"]?> nu stiu cat este de corect insa dupa ce am transformat cateva din instantele gasite am observat ca problemele s-au mai remediat.

**Comment by tetele** [comment]
Se cheama [PHP Short Tags](http://www.php.net/manual/en/ini.core.php#ini.short-open-tag) si sunt acceptbile, atata vreme cat exista o directiva in php.ini care spune lucrul asta. Not a bug.

**Comment by davidutzus** [comment]
si daca unul din posibili utilizatori ai 2PCMS nu are activat PHP Short Tags!?

**Comment by tetele** [comment]
Sa-l activeze :)
